import {
  AlignLeft,
  ArrowRightLeft,
  BadgeInfo,
  Binary,
  Braces,
  CalendarClock,
  CaseSensitive,
  Clock,
  Fingerprint,
  GitCompare,
  KeyRound,
  KeySquare,
  Link2,
  Regex,
  Search,
  ShieldCheck,
  Shuffle,
  TableProperties,
  Tag,
  TextCursorInput,
} from "lucide-solid";
import type { JSX } from "solid-js";

export const ICON_MAP: Record<string, (props: { size?: number; class?: string }) => JSX.Element> = {
  KeyRound: (p) => <KeyRound {...p} />,
  GitCompare: (p) => <GitCompare {...p} />,
  Binary: (p) => <Binary {...p} />,
  Braces: (p) => <Braces {...p} />,
  Fingerprint: (p) => <Fingerprint {...p} />,
  Shuffle: (p) => <Shuffle {...p} />,
  Clock: (p) => <Clock {...p} />,
  Regex: (p) => <Regex {...p} />,
  CaseSensitive: (p) => <CaseSensitive {...p} />,
  TextCursorInput: (p) => <TextCursorInput {...p} />,
  KeySquare: (p) => <KeySquare {...p} />,
  Link2: (p) => <Link2 {...p} />,
  BadgeInfo: (p) => <BadgeInfo {...p} />,
  ArrowRightLeft: (p) => <ArrowRightLeft {...p} />,
  AlignLeft: (p) => <AlignLeft {...p} />,
  Tag: (p) => <Tag {...p} />,
  TableProperties: (p) => <TableProperties {...p} />,
  ShieldCheck: (p) => <ShieldCheck {...p} />,
  Search: (p) => <Search {...p} />,
  CalendarClock: (p) => <CalendarClock {...p} />,
};
