name: PR Title

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  title-check:
    name: title-check
    uses: abijith-suresh/workflows/.github/workflows/conventional-commit-title.yml@a53b4c876bca362ca058c99c01c4c0a955d71c9d # 0.7.0
    permissions:
      pull-requests: read

  pr-title:
    name: pr-title
    if: always()
    needs: title-check
    runs-on: ubuntu-latest

    steps:
      - name: Check required title job
        run: |
          if [[ "${{ needs.title-check.result }}" != "success" ]]; then
            echo "title-check must pass" >&2
            exit 1
          fi
