name: Dependabot auto-merge

on: pull_request_target

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: dependabot-auto-merge
  cancel-in-progress: false

jobs:
  dependabot:
    name: dependabot
    uses: abijith-suresh/workflows/.github/workflows/dependabot-auto-merge.yml@6838f8e2495013c024606bbf8d63d3d5c66344fa # 0.8.0
    permissions:
      contents: write
      pull-requests: write
