name: Clean up Vercel preview deployments

on:
  pull_request_target:
    types:
      - closed

permissions:
  pull-requests: read

concurrency:
  group: vercel-preview-cleanup-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  cleanup:
    uses: abijith-suresh/workflows/.github/workflows/vercel-preview-cleanup.yml@a53b4c876bca362ca058c99c01c4c0a955d71c9d # 0.7.0
    with:
      vercel_project: unwrapped-tools
      vercel_scope: abijiths-projects-1
    secrets:
      vercel_token: ${{ secrets.VERCEL_TOKEN }}
