name: Clean up Vercel preview deployments

on:
  pull_request_target:
    types:
      - closed

permissions:
  pull-requests: read

concurrency:
  group: vercel-preview-cleanup-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  cleanup:
    uses: abijith-suresh/workflows/.github/workflows/vercel-preview-cleanup.yml@6838f8e2495013c024606bbf8d63d3d5c66344fa # 0.8.0
    with:
      vercel_project: unwrapped-tools
      vercel_scope: abijiths-projects-1
    secrets:
      vercel_token: ${{ secrets.VERCEL_TOKEN }}
